apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: 287489840086.dkr.ecr.ap-southeast-1.amazonaws.com/ecr_repo:50
          ports:
            - containerPort: 8080
